/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:27733448-5c1a-4de7-afa7-ac8ad3edf854",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_mNXUGZS1Z",
    "aws_user_pools_web_client_id": "6rkd8gif6ns49v3f42b5u63p6j",
    "oauth": {}
};


export default awsmobile;
